name: Echo Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  echo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Echo Message
        run: echo "Hello, this is a GitHub Actions workflow!"
